/**
 * Generates `scripts/src/import-mlit/station-romanization.ts` — the checked-in table
 * mapping every Tokyo station's Japanese name to its English form.
 *
 * The table is generated once and committed, not resolved at import time: the sources
 * are network services, and a name that silently changes between imports would silently
 * change what the UI says. Committing it also makes every entry reviewable in a diff,
 * which matters most for the entries a model supplied.
 *
 * Source precedence, highest first:
 *   1. wikidata-tokyo  — Wikidata stations administratively inside Tokyo. Geographically
 *                        correct, so it settles collisions the national set cannot
 *                        (Koto's 大島 is Ojima; elsewhere in Japan it is Oshima).
 *   2. wikidata        — Wikidata stations anywhere in Japan, used only when exactly one
 *                        distinct English form exists for the name.
 *   3. japanpost       — the Japan Post town archive already used for localities. Its
 *                        convention is unhyphenated, so compound names sourced here may
 *                        need a hand edit; the `source` field makes them easy to find.
 *   4. model           — hand-reviewable fallback in station-romanization-model.json for
 *                        names no source covers. Nothing here is inferred at runtime.
 *
 * Run: pnpm build:station-romanization
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { normalizeForMatch, parseJapanPostCsv } from "./import-localities/romanization.js";

const OUT = "scripts/src/import-mlit/station-romanization.ts";
const MODEL_FILE = "scripts/src/import-mlit/station-romanization-model.json";
const RESIDUAL_FILE = "/tmp/station-residual.json";

export type RomanizationSource = "wikidata-tokyo" | "wikidata" | "japanpost" | "model";

function stripMacrons(value: string): string {
  return value.normalize("NFD").replace(/[̄]/gu, "").normalize("NFC");
}

function cleanEnglish(value: string): string {
  return stripMacrons(value)
    .replace(/\s+Station$/iu, "")
    .trim();
}

function indexWikidata(pairs: readonly (readonly [string, readonly string[]])[]): Map<string, Set<string>> {
  const index = new Map<string, Set<string>>();
  for (const [ja, ens] of pairs) {
    const key = normalizeForMatch(ja.replace(/駅$/u, ""));
    if (!key) continue;
    for (const en of ens) {
      const value = cleanEnglish(en);
      if (!value) continue;
      const set = index.get(key) ?? new Set<string>();
      set.add(value);
      index.set(key, set);
    }
  }
  return index;
}

function only(set: Set<string> | undefined): string | null {
  if (!set || set.size !== 1) return null;
  return [...set][0] ?? null;
}

function stationNames(): string[] {
  const geo = JSON.parse(readFileSync("data/stations.geojson", "utf8")) as {
    features: { properties: Record<string, unknown> }[];
  };
  const names = new Set<string>();
  for (const f of geo.features) {
    const n = f.properties["N02_005"] ?? f.properties["name_ja"];
    if (typeof n === "string" && n.trim()) names.add(n.trim());
  }
  return [...names].sort();
}

export function buildStationRomanization(): { written: number; residual: string[] } {
  const tokyo = indexWikidata(
    JSON.parse(readFileSync("/tmp/wd-tokyo.json", "utf8")) as [string, string[]][],
  );
  const national = indexWikidata(
    JSON.parse(readFileSync("/tmp/wd-stations.json", "utf8")) as [string, string[]][],
  );

  const post = new Map<string, Set<string>>();
  for (const row of parseJapanPostCsv(readFileSync("data/locality-romanization.csv"))) {
    const set = post.get(row.matchKey) ?? new Set<string>();
    set.add(row.nameEn);
    post.set(row.matchKey, set);
  }

  const model = new Map<string, string>(
    existsSync(MODEL_FILE)
      ? Object.entries(JSON.parse(readFileSync(MODEL_FILE, "utf8")) as Record<string, string>)
      : [],
  );

  const resolved: { ja: string; en: string; source: RomanizationSource }[] = [];
  const residual: string[] = [];
  for (const ja of stationNames()) {
    const key = normalizeForMatch(ja);
    const fromModel = model.get(ja);
    const en =
      only(tokyo.get(key)) ??
      only(national.get(key)) ??
      only(post.get(key)) ??
      fromModel ??
      null;
    if (en === null) {
      residual.push(ja);
      continue;
    }
    const source: RomanizationSource = only(tokyo.get(key))
      ? "wikidata-tokyo"
      : only(national.get(key))
        ? "wikidata"
        : only(post.get(key))
          ? "japanpost"
          : "model";
    resolved.push({ ja, en, source });
  }

  const lines = [
    "// GENERATED by pnpm build:station-romanization — but committed, reviewed and",
    "// hand-editable. Correct a wrong reading here and it survives regeneration only if",
    "// you also add it to station-romanization-model.json, which wins over every source",
    "// except Wikidata. `source` records where each name came from; `model` entries were",
    "// supplied by a language model and carry the least authority.",
    "",
    "export interface StationRomanization {",
    "  readonly ja: string;",
    "  readonly en: string;",
    '  readonly source: "wikidata-tokyo" | "wikidata" | "japanpost" | "model";',
    "}",
    "",
    "export const STATION_ROMANIZATION: readonly StationRomanization[] = [",
    ...resolved.map(
      (r) =>
        `  { ja: ${JSON.stringify(r.ja)}, en: ${JSON.stringify(r.en)}, source: ${JSON.stringify(r.source)} },`,
    ),
    "];",
    "",
  ];
  writeFileSync(OUT, lines.join("\n"));
  writeFileSync(RESIDUAL_FILE, JSON.stringify(residual, null, 2));
  return { written: resolved.length, residual };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { written, residual } = buildStationRomanization();
  const counts = new Map<string, number>();
  for (const line of readFileSync(OUT, "utf8").split("\n")) {
    const m = /source: "([a-z-]+)"/u.exec(line);
    if (m?.[1]) counts.set(m[1], (counts.get(m[1]) ?? 0) + 1);
  }
  console.log(`build:station-romanization — ${String(written)} resolved`);
  for (const [source, n] of [...counts].sort()) console.log(`  ${source}: ${String(n)}`);
  console.log(`  unresolved (written to ${RESIDUAL_FILE}): ${String(residual.length)}`);
}
